name: Ci for flask App

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run Linting
        run: |
          flake8 app

      - name: Run unit tests
        run: |
          pytest tests/

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Builddx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERS_USERNAME }}
          password: ${{ secrets.DOCKERS_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: harsh0031/flask-docker-app:latest
      

